services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    deploy:
      restart_policy:
        condition: on-failure


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.1
    container_name: kibana
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    deploy:
      restart_policy:
        condition: on-failure