services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      restart_policy:
        condition: on-failure