services:
  mongo:
    image: mongo:3.2.7
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081


########### 在demo库中分配用户权限 ############ 
# use demo
# db.createUser(
#     {
#       user: "demo",
#       pwd: "demo",
#       roles: [ 
#            { role: "readWrite", db: "demo" }
#       ]
# })